### ISSUE TITLE
DATA FORMAT ISSUE in data sanititazion code

### ISSUE THREAD

**Issue by deepakkuk** [Maddosaurus/Master_IPython#1]
![screenshot from 2018-12-27 15-14-28](https://user-images.githubusercontent.com/33250220/50475268-250b3700-09ea-11e9-992d-561c859c9d41.png)
IN GIVEN CODE LINE NO.34 face error.
IS BOTH COMMENT IN LINE 34 HAVE SAME RESULT

**Comment by Maddosaurus** [comment]
It seems like the original CSV changed since I've downloaded it. The timestamp format might have been changed or fixed in this version. As you can see, I defined three different time parsing methods in lines 20, 31 and 42 (see for example here: https://github.com/Maddosaurus/MLT/blob/master/MLT/datasets/sanitizeCIC.py#L20 )  
Have a look in your version of the CSV and pick the right version for the date format used. That should get you up and running!
