### ISSUE TITLE
in data Sanititazion.ipynb got error while includes the missing field "external_ip")

### ISSUE THREAD

**Issue by deepakkuk** [Maddosaurus/Master_IPython#3]
![screenshot from 2018-12-27 15-54-02](https://user-images.githubusercontent.com/33250220/50476835-c5b02580-09ef-11e9-902b-d3c400895e71.png)
it show "ValueError: Writing 85 cols but got 86 aliases"

**Comment by Maddosaurus** [comment]
Looks like the download of the CSV files changed since the last time I've downloaded it.  
In other words: It might not be neccecary anymore to rewrite the header.  
I am currently in the process of rewriting the whole Notebook collection into a Python Module. Therefore, I don't have the resources to fix and adapt to this changes. The rewrite that adresses these problems will be available soon.
